version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5089
      POSTGRES_DB: yelp
    ports:
      - "5434:5432"  
    volumes:
      - ./yelp_database_dump.sql:/docker-entrypoint-initdb.d/yelp_database_dump.sql 

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:5089@db:5432/yelp  
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3001:3000"
    depends_on:
      - server
