name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.4.1'

    - name: Install dependencies
      run: npm install
      working-directory: server

    - name: Build Docker image
      run: docker build -t backend-app:22.4.1 ./server

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_docker_image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-66-199-220.ap-south-1.compute.amazonaws.com 
        username: ubuntu 
        key: ${{ secrets.EC2_SSH_KEY }} 
        port: 22
        script: |
          cd ~/Github-Action
          git pull origin main
          docker-compose down
          docker-compose build server
          docker-compose up -d server
