name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.4.1'

    - name: Install dependencies
      run: npm install
      working-directory: client

    - name: Build Docker image
      run: docker build -t frontend-app:latest .
      working-directory: client


    - name: SSH into EC2 and deploy frontend
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ec2-52-66-199-220.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22    
        script: |
          cd ~/Github-Action-Frontend
          docker-compose down
          docker-compose up -d
